Repository blackbaud/skyux2, pull requests merged in 2018-08, with the labels that each got.

#1876 Various Colorpicker Issues
  src/modules/colorpicker/colorpicker-input.directive.ts
  src/modules/colorpicker/colorpicker.component.html
  src/modules/colorpicker/colorpicker.component.spec.ts
  src/modules/colorpicker/colorpicker.component.ts
  src/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
  src/modules/colorpicker/index.ts
  src/modules/colorpicker/types/colorpicker-result.ts
  src/modules/colorpicker/types/index.ts
Labels: Status: Ready to merge

#1887 Fix issues with tabs that are activated via an ngIf
  src/modules/tabs/fixtures/tabset.component.fixture.html
  src/modules/tabs/tabset.component.spec.ts
  src/modules/tabs/tabset.component.ts
Labels: Priority: Medium, Status: Ready to merge

#1897 List view grid column change event
  src/modules/grid/grid.component.spec.ts
  src/modules/grid/grid.component.ts
  src/modules/list-view-grid/fixtures/list-view-grid-dynamic.component.fixture.ts
  src/modules/list-view-grid/list-view-grid.component.spec.ts
  src/modules/list-view-grid/list-view-grid.component.ts
Labels: Priority: Medium, Status: Ready to merge

#1900 Contrib > Checklist "show selected items"
  skyux-spa-visual-tests/screenshots-baseline/list-View-Checklist-Checked-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/list-View-Checklist-Single-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/list-View-Checklist-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/src/app/list-view-checklist/list-view-checklist.visual-spec.ts
  src/locales/resources_en_US.json
  src/modules/filter/filter-button.component.html
  src/modules/filter/filter-button.component.ts
  src/modules/list-column-selector-action/list-column-selector-action.spec.ts
  src/modules/list-data-provider-in-memory/list-data-in-memory.provider.ts
  src/modules/list-toolbar/list-toolbar.component.html
  src/modules/list-toolbar/list-toolbar.component.scss
  src/modules/list-toolbar/list-toolbar.component.ts
  src/modules/list-view-checklist/fixtures/list-view-checklist-toolbar.component.fixture.html
  src/modules/list-view-checklist/fixtures/list-view-checklist-toolbar.component.fixture.ts
  src/modules/list-view-checklist/list-view-checklist.component.html
  src/modules/list-view-checklist/list-view-checklist.component.scss
  src/modules/list-view-checklist/list-view-checklist.component.spec.ts
  src/modules/list-view-checklist/list-view-checklist.component.ts
  src/modules/list/list-data-request.model.ts
  src/modules/list/list.component.ts
  src/modules/list/state/list-state-action.type.ts
  src/modules/list/state/list-state.rxstate.ts
  src/modules/list/state/toolbar/actions.ts
  src/modules/list/state/toolbar/disable.action.ts
  src/modules/list/state/toolbar/toolbar.model.ts
  src/modules/list/state/toolbar/toolbar.orchestrator.ts
  src/modules/search/search.component.html
  src/modules/search/search.component.ts
  src/modules/select-field/select-field.component.spec.ts
Labels: From: Consumer, Priority: High, Status: Ready to merge

#1915 Contrib > fix sort button label
  src/modules/dropdown/dropdown-menu.component.html
  src/modules/dropdown/dropdown-menu.component.ts
  src/modules/sort/sort-item.component.html
  src/modules/sort/sort.component.html
  src/modules/sort/sort.component.spec.ts
  src/modules/sort/sort.component.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1913 Consistent styles for select field
  src/scss/_theme.scss
Labels: From: Consumer, Priority: Low, Status: Ready to merge, Type: Bug

#1884 Popover hover close fix
  src/modules/popover/popover.component.ts
  src/modules/popover/popover.directive.spec.ts
  src/modules/popover/popover.directive.ts
Labels: Priority: Medium, Status: Ready to merge

#1919 Fix for issues with definition list in repeaters
  src/modules/definition-list/definition-list-value.component.html
Labels: From: Consumer, Priority: Low, Status: Ready to merge, Type: Bug

#1896 Contrib > Action button link
  skyux-spa-visual-tests/screenshots-baseline/action-Button-Container-Small-chrome-480x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/action-Button-Container-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/src/app/action-button/action-button-visual.component.html
  src/demos/action-button/action-button-demo.component.html
  src/modules/action-button/action-button-icon.component.html
  src/modules/action-button/action-button-icon.component.ts
  src/modules/action-button/action-button.component.html
  src/modules/action-button/action-button.component.scss
  src/modules/action-button/action-button.component.spec.ts
  src/modules/action-button/action-button.component.ts
  src/modules/action-button/action-button.module.ts
  src/modules/action-button/fixtures/action-button.component.fixture.html
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1924 Switched the action button url to permalink
  skyux-spa-visual-tests/src/app/action-button/action-button-visual.component.html
  skyux-spa-visual-tests/src/app/action-button/action-button-visual.component.ts
  src/demos/action-button/action-button-demo.component.html
  src/demos/action-button/action-button-demo.component.ts
  src/modules/action-button/action-button.component.html
  src/modules/action-button/action-button.component.spec.ts
  src/modules/action-button/action-button.component.ts
  src/modules/action-button/action-button.module.ts
  src/modules/action-button/fixtures/action-button.component.fixture.html
  src/modules/action-button/fixtures/action-button.component.fixture.ts
  src/modules/action-button/index.ts
  src/modules/action-button/types/action-button-permalink.ts
  src/modules/action-button/types/index.ts
Labels: Status: Ready for review

#1920 Added fluid grid container
  src/demos/fluid-grid/fluid-grid-demo.component.html
  src/modules/fluid-grid/fluid-grid.component.html
  src/modules/fluid-grid/fluid-grid.component.scss
  src/modules/fluid-grid/fluid-grid.component.ts
  src/modules/fluid-grid/fluid-grid.module.ts
  src/modules/fluid-grid/index.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1926 Popover z-index set to 1001
  src/scss/_variables.scss
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1895 Contrib > Timepicker visual tests
  skyux-spa-visual-tests/src/app/timepicker/index.html
  skyux-spa-visual-tests/src/app/timepicker/timepicker-visual.component.html
  skyux-spa-visual-tests/src/app/timepicker/timepicker-visual.component.ts
  skyux-spa-visual-tests/src/app/timepicker/timepicker.visual-spec.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1931 Fix plunker issues found while fixing select field plunker
  src/demos/demo.service.ts
  src/demos/infinite-scroll/infinite-scroll-demo.component.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1937 Tile Dashboard Initialization Event
  src/modules/tiles/tile-dashboard/tile-dashboard.service.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge

#1938 Doc tweak to changelog
  CHANGELOG.md
Labels: Status: Ready to merge

#1928 Lookup & Autocomplete error state fixes
  src/modules/autocomplete/autocomplete-input.directive.ts
  src/modules/autocomplete/autocomplete.component.spec.ts
  src/modules/lookup/lookup.component.scss
Labels: From: Consumer, Priority: Low, Status: Ready to merge, Type: Bug

#1947 Added css to allow for text wrapping for toast contents
  src/modules/toast/toast.component.scss
Labels: From: Consumer, Priority: Low, Status: Ready for review, Type: Bug

#1728 Progress indicator component (#1727)
  skyux-spa-visual-tests/src/app/app-extras.module.ts
  skyux-spa-visual-tests/src/app/progress-indicator/index.html
  skyux-spa-visual-tests/src/app/progress-indicator/progress-indicator-horizontal-visual.component.html
  skyux-spa-visual-tests/src/app/progress-indicator/progress-indicator-horizontal-visual.component.ts
  skyux-spa-visual-tests/src/app/progress-indicator/progress-indicator-visual.component.html
  skyux-spa-visual-tests/src/app/progress-indicator/progress-indicator-visual.component.ts
  skyux-spa-visual-tests/src/app/progress-indicator/progress-indicator.visual-spec.ts
  src/core.ts
  src/demo.ts
  src/demos/demo.service.ts
  src/demos/index.ts
  src/demos/progress-indicator/index.ts
  src/demos/progress-indicator/progress-indicator-demo-context.ts
  src/demos/progress-indicator/progress-indicator-demo-form.component.html
  src/demos/progress-indicator/progress-indicator-demo-form.component.ts
  src/demos/progress-indicator/progress-indicator-demo.component.html
  src/demos/progress-indicator/progress-indicator-demo.component.scss
  src/demos/progress-indicator/progress-indicator-demo.component.ts
  src/demos/progress-indicator/progress-indicator-horizontal-demo.component.html
  src/demos/progress-indicator/progress-indicator-horizontal-demo.component.ts
  src/modules/progress-indicator/fixtures/progress-indicator.component.fixture.html
  src/modules/progress-indicator/fixtures/progress-indicator.component.fixture.ts
  src/modules/progress-indicator/index.ts
  src/modules/progress-indicator/progress-indicator-item/index.ts
  src/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.html
  src/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.scss
  src/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.ts
  src/modules/progress-indicator/progress-indicator-nav-button/index.ts
  src/modules/progress-indicator/progress-indicator-nav-button/progress-indicator-nav-button.component.html
  src/modules/progress-indicator/progress-indicator-nav-button/progress-indicator-nav-button.component.ts
  src/modules/progress-indicator/progress-indicator-reset-button/index.ts
  src/modules/progress-indicator/progress-indicator-reset-button/progress-indicator-reset-button.component.html
  src/modules/progress-indicator/progress-indicator-reset-button/progress-indicator-reset-button.component.scss
  src/modules/progress-indicator/progress-indicator-reset-button/progress-indicator-reset-button.component.ts
  src/modules/progress-indicator/progress-indicator-title/index.ts
  src/modules/progress-indicator/progress-indicator-title/progress-indicator-title.component.html
  src/modules/progress-indicator/progress-indicator-title/progress-indicator-title.component.scss
  src/modules/progress-indicator/progress-indicator-title/progress-indicator-title.component.ts
  src/modules/progress-indicator/progress-indicator.component.html
  src/modules/progress-indicator/progress-indicator.component.scss
  src/modules/progress-indicator/progress-indicator.component.spec.ts
  src/modules/progress-indicator/progress-indicator.component.ts
  src/modules/progress-indicator/progress-indicator.module.ts
  src/modules/progress-indicator/types/index.ts
  src/modules/progress-indicator/types/progress-indicator-change.ts
  src/modules/progress-indicator/types/progress-indicator-message-type.ts
  src/modules/progress-indicator/types/progress-indicator-mode.ts
Labels: From: Consumer, Priority: High, Status: Ready for review, sky-progress-indicator

#1944 714 list view grid highlighting
  skyux-spa-visual-tests/src/app/grid/grid-visual.component.html
  skyux-spa-visual-tests/src/app/grid/grid-visual.component.ts
  skyux-spa-visual-tests/src/app/grid/grid.visual-spec.ts
  src/modules/grid/grid-column.component.ts
  src/modules/grid/grid-column.model.ts
  src/modules/grid/grid.component.html
  src/modules/grid/grid.component.ts
  src/modules/grid/grid.module.ts
  src/modules/list-view-grid/list-view-grid.component.html
  src/modules/list-view-grid/list-view-grid.component.spec.ts
  src/modules/list-view-grid/list-view-grid.component.ts
Labels: From: Consumer, Priority: Low, Status: Ready to merge, Type: Enhancement

#1892 Radio and checkbox icon buttons
  package.json
  skyux-spa-visual-tests/package.json
  skyux-spa-visual-tests/src/app/checkbox/checkbox-visual.component.html
  skyux-spa-visual-tests/src/app/checkbox/checkbox.visual-spec.ts
  skyux-spa-visual-tests/src/app/radio/radio-visual.component.html
  skyux-spa-visual-tests/src/app/radio/radio-visual.component.ts
  skyux-spa-visual-tests/src/app/radio/radio.visual-spec.ts
  src/demos/checkbox/checkbox-demo.component.html
  src/demos/checkbox/checkbox-demo.component.ts
  src/demos/list-toolbar/list-toolbar-demo.component.html
  src/demos/list-toolbar/list-toolbar-demo.component.ts
  src/demos/radio/radio-demo.component.html
  src/demos/radio/radio-demo.component.ts
  src/modules/checkbox/checkbox.component.html
  src/modules/checkbox/checkbox.component.scss
  src/modules/checkbox/checkbox.component.spec.ts
  src/modules/checkbox/checkbox.component.ts
  src/modules/checkbox/checkbox.module.ts
  src/modules/icon/icon.component.scss
  src/modules/radio/radio.component.html
  src/modules/radio/radio.component.scss
  src/modules/radio/radio.component.spec.ts
  src/modules/radio/radio.component.ts
  src/modules/radio/radio.module.ts
Labels: From: Consumer, Priority: Medium, Status: Ready to merge, sky-checkbox, sky-radio

#1954 Release 2.22.0
  CHANGELOG.md
  package.json
Labels: Status: Ready for review

#1948 Updated colorpicker css styles to remove extra pixels
  src/modules/colorpicker/colorpicker.component.scss
Labels: From: Consumer, Priority: Low, Status: Ready to merge, Type: Bug
