Repository blackbaud/skyux2, pull requests merged in 2018-09, with the labels that each got.

#1958 Fixes vertical tab regression
  src/modules/vertical-tabset/vertical-tabset-group.component.html
  src/modules/vertical-tabset/vertical-tabset-group.component.scss
Labels: Difficulty: Low, Priority: High, Status: Ready to merge, Type: Bug

#1961 Fixed SkyWaitModule SkyWindowRefService provider issue
  src/modules/wait/wait.module.ts
  src/modules/wait/wait.service.spec.ts
Labels: From: Consumer, Priority: Medium, Status: Ready to merge, Type: Bug

#1925 Changes to fix issues with the spacing for repeaters
  skyux-spa-visual-tests/screenshots-baseline/infinite-Scroll-Nobutton-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/infinite-Scroll-Wait-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/infinite-Scroll-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/repeater-Collapsed-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/repeater-Multiple-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/repeater-Single-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/repeater-chrome-1000x800-dpr-1.png
  src/modules/repeater/repeater-item.component.scss
Labels: Priority: Low, Status: Ready to merge

#1968 disabled aria-controls when the target has not been drawn
  package.json
  skyux-spa-visual-tests/package.json
  skyux-spa-visual-tests/screenshots-baseline/list-Toolbar-Small-chrome-400x800-dpr-1.png
  skyux-spa-visual-tests/screenshots-baseline/list-Toolbar-chrome-1000x800-dpr-1.png
  skyux-spa-visual-tests/src/app/list-toolbar/list-toolbar-visual.component.html
  skyux-spa-visual-tests/src/app/list-toolbar/list-toolbar-visual.component.ts
  skyux-spa-visual-tests/src/app/list-toolbar/list-toolbar.visual-spec.ts
  src/modules/list-filters/list-filter-inline.component.spec.ts
  src/modules/list-toolbar/list-toolbar.component.html
  src/modules/list-toolbar/list-toolbar.component.ts
Labels: From: Consumer, Priority: High, Status: In progress, sky-listbuilder
